<?php
/**
 * Created by PhpStorm.
 * User: JV
 * Date: 2016/9/24
 * Time: 下午3:18
 */

interface Decorator
{
    public function display();
}

class Girl implements Decorator
{
    private $name;
    public function __construct($name)
    {
        $this->name = $name;
    }

    public function display()
    {
        // TODO: Implement display() method.
        echo 'i am '.$this->name.'i am outting!!'.PHP_EOL;
    }
}

class Finery implements Decorator
{
    private $component;

    public function __construct(Decorator $component)
    {
        $this->component = $component;
    }
    public function display()
    {
        // TODO: Implement display() method.
        $this->component->display();
    }
}

class Shoes extends Finery
{
    public function display()
    {
        echo '穿上鞋子'.PHP_EOL;
        parent::display(); // TODO: Change the autogenerated stub

    }
}

class Skirt extends Finery
{
    public function display()
    {
        echo '穿上裙子'.PHP_EOL;
        parent::display(); // TODO: Change the autogenerated stub

    }
}

class Fire extends Finery
{
    public function display()
    {
        echo '出门前先整理头发'.PHP_EOL;
        parent::display(); // TODO: Change the autogenerated stub
        echo '出门后在整理一下头发'.PHP_EOL;
    }
}

$girl = new Girl('fancy');
$shoes = new Shoes($girl);
$skirt = new Skirt($shoes);
$fire = new Fire($skirt);
$fire->display();